<?xml version="1.1" encoding="UTF-8"?>

<!DOCTYPE TEI [
  <!ELEMENT TEI (header, facsimile?, testo+) >
  <!ELEMENT header (#PCDATA)>
  <!ELEMENT facsimile (#PCDATA)>
  <!ELEMENT testo (#PCDATA| seg)* >
  <!ELEMENT seg (#PCDATA)>
  <!ATTLIST header type CDATA #FIXED "intestazione">
  <!ATTLIST header lang NMTOKEN #IMPLIED >
  <!ATTLIST facsimile source CDATA #REQUIRED>
  <!ATTLIST facsimile ref IDREFS #IMPLIED>
  <!ATTLIST testo id ID #REQUIRED>
  <!ATTLIST testo type CDATA #IMPLIED>  
  
]>

<TEI>
  <header >Prova</header>
  <facsimile source="prova" >testo</facsimile>  
  <testo id="prova">tutto<seg>uu</seg> ok</testo>
  

</TEI>